### ISSUE TITLE
Transformation page

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/epsg.io#100]
Create page on  /trasform/ with inputs for coordinates transformation and results list. Coordinate selector like maptiler's one: http://www.maptiler.com/how-to/coordinate-systems/
https://github.com/klokan/statoil/issues/6

Redirect /trans/ without parameters to this page.

In future: batch from file, drag and drop.

**Comment by daliborjanak** [comment]
Initial template done. @petrsloup, you can continue with javascript. I don't know how much form field you will need so i can finish later. Also it will need some responsive fixes.

**Comment by petrsloup** [comment]
Implementation done in new-js branch (https://github.com/klokantech/epsg.io/tree/new-js).

Improved styling and responsiveness to be done by @daliborjanak now.

**Comment by daliborjanak** [comment]
Now it looks better and it's responsive. Works great

@petrsloup can you please highlight captions ("Unit:" etc.) like on page: http://epsg.io/3138 (bolt, black). It requires to add span with javascript.

Also "show full details in new window" should be renamed: "show details" or "coordinate system detail". Color shoud be like link or add class="btn-dark" on it.

**Comment by petrsloup** [comment]
@daliborjanak Done. (The captions are part of the template, so no javascript change was required.)

**Comment by klokan** [comment]
Can this be merged now or it needs more work?

**Comment by daliborjanak** [comment]
This issue should be merged but i think iťs in branch together with #97. #97 is not read yet

**Comment by petrsloup** [comment]
Yes, the `/transform` page is complete, but the `new-js` branch should not be merged before the `/map` page is further discussed.

**Comment by petrsloup** [comment]
Done in #106
