### ISSUE TITLE
/transform usability improvements

### ISSUE THREAD

**Issue by petrsloup** [klokantech/epsg.io#109]
- [x] Always show some default SRSs (4326; or 4326 and 3857 when both are missing)
- [x] Degree formatting cycling button (decimal -> DM -> DMS)
- [x] Do not show "Show position on a map" when not possible !
- [x] Align "Latitude" and "Longitude" labels

**Comment by petrsloup** [comment]
This batch of improvements is probably done now.

@klokan We need CDN reset for this, https://github.com/klokantech/epsg.io/issues/107 and https://github.com/klokantech/epsg.io/issues/110.

**Comment by klokan** [comment]
IDEA: Picking from the location in a different browser window could be implemented via a per domain shared localStorage in JavaScript:
http://stackoverflow.com/questions/4201239/in-html5-is-the-localstorage-object-isolated-per-page-domain
