### ISSUE TITLE
When epsg.io is accessed via https, the map service cannot be used with the latest Chrome

### ISSUE THREAD

**Issue by r0x0r** [klokantech/epsg.io#111]
Mixed Content: The page at 'https://epsg.io/map#srs=3134' was loaded over HTTPS, but requested an insecure script 'http://maps.google.com/maps/api/js?v=3.3&sensor=false'. This request has been blocked; the content must be served over HTTPS.
Uncaught ReferenceError: google is not defined

**Comment by klokan** [comment]
Regression on latest deploy. All resources in /map and /transcribe must be loaded via https.

@petrsloup could you please fix and redeploy?

**Comment by petrsloup** [comment]
@klokan Done, please close this ticket after CDN reset.

**Comment by klokan** [comment]
CDN flushed. Closing.
