### ISSUE TITLE
EPSG 8.9 data

### ISSUE THREAD

**Issue by klokan** [klokantech/epsg.io#112]
> On 15th February 2015, EPSG Dataset ver 8.9 was released (Access and SQL download). Version 8.9 replaces version 8.8 of 2015-11-22 and includes the revisions made only in the on-line registry in version 8.8.1. New to version 8.9: - Changes as documented in Change Records through 2016.009, but with actions still remaining on some change requests. - Significant revisions to data for Cyprus. - Minor revisions to data for Canada, Ireland and United Kingdom. - An error in time-dependent transformations caused by a problem in the creation of the v8.8 Access database and then the SQL files downloadable from the EPSG web site (www.epsg.org) has been corrected. This problem did not affect on-line registry (www.epsg-registry.org) content or export. Thank you. EPSG

**Comment by TomPohys** [comment]
Solved by commits 7af60953898ffdb0979c6d42a3196a9404655bbf, 6618c3b914f234c1469189feb4a0d43f1f6ea59b, 36eb4a985084e11502532dba3105004ca06facb7 in branch 8.9
