### ISSUE TITLE
UX improvements

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/epsg.io#114]
Homepage:
- [x] move blue buttons under searchbox
- [x] If someone add address to input and there will be not results. We would like to check if it's an address via google api. If it is address display centered map and button with "Coordinates on map >"
- [x] Switch blue buttons order

CRS page:
- [x] display buton "Transform coordinates >" this will open a page. Input crs from page and output 4326. Add title to link for seo. Button's labels same as homepage. Move buttons under social icons (right, top)

Results page:
- [x] result item is followed by link to map, we need to add another link to transform

Transform page:
- [x] Reorder in box: Input CRS, input coordinates, details (remove title of this section), link show more details (remove "show")
- [x] Change title of page: Transform coordinates - GPS online convertor
- [x] Strapline: Online convertor for lat & long coordinates and projected systems

Map page:
- [x] title: Coordinates on a map - pick GPS lat & long or coordinates in a projection system

**Comment by klokan** [comment]
Everything now looks really much better then before this ticket. Whow! Thanks!

Unfortunately, some small visual issues with the new layout:
![Uploading Screen Shot 2016-03-03 at 18.12.19.png…]()
![screen shot 2016-03-03 at 18 13 20](https://cloud.githubusercontent.com/assets/59284/13502579/d31669b4-e16b-11e5-8701-4c580744ed38.png)

**Comment by klokan** [comment]
The blue button and even smaller map (next to the address) would probably look better on the result page for address query.
