### ISSUE TITLE
api terms and conditions?

### ISSUE THREAD

**Issue by scuerda** [klokantech/epsg.io#117]
Thanks for your hard work on this excellent resource. I'm looking to solve a problem ( ckan/ckanext-geoview/issues/40 ) re: programmatic look up of proj4 strings.

One solution that I've proposed is to query against the epsg.io api for unknown or undefined proj4 string ids. Are their rate limits and/or terms that would be violated by implementing such a solution within a ckan extension? This might end up being a short-term solution, to be replaced with a native load of epsg db.

Thanks.

**Comment by klokan** [comment]
No restriction in this moment, but also no guarantee of availability of the service.

You may launch your own instance on your own server with docker easily (one command).

We would be very interested to work on a packed "epsg db" in sqlite for free redistribution - if there is a customer willing to support our working time. The idea of data.epsg.io is based around that... hope to speak about it more on this year FOSS4G.

**Comment by scuerda** [comment]
Thanks for the quick response.
