### ISSUE TITLE
Website is offline No cached version of this page is available.

### ISSUE THREAD

**Issue by drnextgis** [klokantech/epsg.io#118]
Trying to open [this](http://epsg.io/3395.js) page.
![screenshot from 2016-04-29 13 07 31](https://cloud.githubusercontent.com/assets/866124/14909253/650f29fc-0e0b-11e6-8611-f48ecf1be719.png)

**Comment by JeffJacobson** [comment]
I'm currently getting the following response from that URL.

    proj4.defs("EPSG:3395","+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs");

**Comment by drnextgis** [comment]
Yes, now origin server is up.

**Comment by klokan** [comment]
Sorry - we had a downtime. We are improving monitoring and alerting process to react faster in future.
