### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by klokan** [klokantech/epsg.io#141]
Let's refresh the design slightly:

- Clear selection of on of 3 different functions (search, map, transform).
- Add navigation to frontpage (About, Transform, ...) and back to Search from other pages
- MapTiler brand, instead of KlokanTech - slight change in colors and title font
- Preserve link GitHub (at least on About page - maybe under menu bar?)
- Social icons - make it clear it means share this page on ... before you click.
- Redo images and .zip on mediakit at /about/

Mockups are being done on Team Drive: https://drive.google.com/drive/u/0/folders/0AE0PS4_1EdERUk9PVA

**Comment by TomasKlanica** [comment]
Last mockups link:
https://drive.google.com/drive/u/0/folders/1hqY8bqUS96ajSJ8IddsJsyzfePIs5UDs

**Comment by daliborjanak** [comment]
![epsg-io-world-system-page-v7a](https://user-images.githubusercontent.com/1891090/47443647-1cfa0580-d7b5-11e8-899d-f5e8838d6db3.png)
![epsg-io-web-2018-7a](https://user-images.githubusercontent.com/1891090/47443648-1cfa0580-d7b5-11e8-8191-20fe3418699c.png)

**Comment by daliborjanak** [comment]
Done and deployed

**Comment by klokan** [comment]
There are bugs:
- invisible text in the main input search bar - if you type...
- broken results page layout (search button after input) - try Chrome on Mac an Safari
- different links in the header on the front page and elsewhere (missing Search, different font and color of text)
- Footer is strange without any text at all - we had a version of EPSG database visible there - now it is gone.
- Frontpage https://epsg.io/ reports JavaScript issue - unsafe scripts (HTTP?)
- We may (at least frontpage) redirect to "https" 

The web feels broken - more than before...

After the changes are deployed (and ideally after small data updates maybe by @) - we need to announce the change on social networks @xkomczax

**Comment by daliborjanak** [comment]
Design updated. Https tracked in https://github.com/klokantech/epsg.io/issues/145
