### ISSUE TITLE
/map on https does not run

### ISSUE THREAD

**Issue by klokan** [klokantech/epsg.io#67]
All /map pages does not run on https:// - because Google Maps API is loaded via http:// protocol.

See:
http://epsg.io/4326/map

Problem is with:
```
 <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
```
replace by https:// and test

**Comment by klokan** [comment]
Forgotten https:// request on Google Static Maps request. Now done in 249d5c81d398b187bd4af4a7eb67b14c2d610878

**Comment by TomPohys** [comment]
And in e5e0a3ba07d4c2bf8ec29e115518608b8936f561

**Comment by klokan** [comment]
Map has submitted the AJAX calls to non-https endpoint. Fast fix: 1109185e6c64f93008848f04263d7d60933bbde9

**Comment by klokan** [comment]
All over the web there is a lot of links to `http://` to epsg.io itself - these should be probably all to `//`

**Comment by klokan** [comment]
or even better relative links starting with `/`

**Comment by klokan** [comment]
Everything seems to be OK on the map page with https. Thanks @TomPohys
