### ISSUE TITLE
Cant find the GmlDictionary.xml file to download

### ISSUE THREAD

**Issue by s093294** [klokantech/epsg.io#71]
I was reading the readme and wanted to try myself to play with the python scripts but I failed at getting access to GmlDictionary.xml.

I end up on this page : http://www.epsg.org/DownloadDataset

and can only download different types of sql files.

**Comment by TomPohys** [comment]
After `login` at http://epsg-registry.org you will able to `export registry` as `Export GML 3.2.1 with EPSG metadata`.

fixed by d7d806167ce88f74fc6e2e304da510743abecc53

**Comment by s093294** [comment]
Ahh thanks. The welcome text told one to download stuff from the other site. Found it.
