### ISSUE TITLE
Error messages are sent in the incorrect format

### ISSUE THREAD

**Issue by dudaerich** [klokantech/epsg.io#79]
The request http://epsg.io/trans?x=50&y=17&z=0&s_srs=55&t_srs=5514&callback=jsonpFunction returns error message in HTML format although the expected format is JSONP. The same problem is in the case of JSON.

**Comment by klokan** [comment]
s_srs=55 is a mistake.

You probably wanted:

http://epsg.io/trans?x=50&y=17&z=0&s_srs=4326&t_srs=5514&callback=jsonpFunction

But we should have a better error message in JSON...

**Comment by dudaerich** [comment]
I have created a pull request that solves this issue https://github.com/klokantech/epsg.io/pull/80

**Comment by klokan** [comment]
The commit is full of empty lines :-(

There is regression on this pull request. List transformation does not run #83

**Comment by dudaerich** [comment]
Sorry for the empty lines.

I created pull request which fix #83. See https://github.com/klokantech/epsg.io/pull/84
