### ISSUE TITLE
Datum transformation not applied in /map

### ISSUE THREAD

**Issue by OASteinlein** [klokantech/epsg.io#87]
In the map window, using ED50 as datum (http://epsg.io/23031/map), conversion from lat, lon to UTM results in wrong UTM easing, northing. Typing in (lat, lon) = (62.0, 3.0) in the input field at the top right, the result at the bottom of the screen is not correct. I get: Easting: 500093.28, Northing: 6874396.79

Using BlueMarble geodetic calculator I get Easting; 500000.0 Northing: 6874345.4

There should be no datum transformation involved. Using http://epsg.io/32631/map and the same parameters the result is: Easting; 500000.0 Northing: 6874180.15 which is equal to the result in BlueMarble. 

What am I doing wrong with ED50?

**Comment by OASteinlein** [comment]
I have tried a bit more and figured out that the coordinates in the upper right of the map window are in WGS84. The projected or converted coordinates at the bottom are in the local coordinate system. BUT: The datum transformations does not work correctly. I used http://epsg.io/4230-1613/map to convert from WGS84 to ED50 in the North Sea and specified EPSG::1613 to do the job. But, in fact the conversion used is EPSG::1133 - DMA ED50 mean!!!

**Comment by klokan** [comment]
As you mentioned, the coordinates in the upper right of the map window are always in WGS84 - which is probably source of confusion on the original problem reported in this ticket.

If we use http://epsg.io/4230 as the datum, and compare the transformation:
- http://epsg.io/1613 (parameters: -90.365, -101.13, -123.384, 0.333, 0.077, 0.894, 1.994), which are correctly visible in the WKT and Proj4 definitions at http://epsg.io/4230-1613 and
- http://epsg.io/1133 (parameters: -87.0, -98.0, -121.0) visible in definitions at  http://epsg.io/4230 and  http://epsg.io/4230-1133/

then both seems to be used correctly on the EPSG.io website...

In the second comment you reported another problem - claiming that when you use in the online interface the transformation 1613 you are getting the same results as with transformation 1133.
I can't reproduce this issue.

There is a different result for transformation 1613 and 1133. The transformation calculated on a command-line delivers the same result as on the website.

<img width="1101" alt="screen shot 2015-10-07 at 13 28 44" src="https://cloud.githubusercontent.com/assets/59284/10336382/aa91633c-6cf8-11e5-85ae-89bdf69ef6dc.png">
http://epsg.io/4230-1613/map

    $ gdaltransform -s_srs epsg:4326 -t_srs "+proj=longlat +ellps=intl +towgs84=-90.365,-101.13,-123.384,0.333,0.077,0.894,1.994 +no_defs"
    3 62
    3.00176338827957 62.000460577362 -38.7094011837617

<img width="1101" alt="screen shot 2015-10-07 at 13 29 24" src="https://cloud.githubusercontent.com/assets/59284/10336390/b465a3c8-6cf8-11e5-921d-ed1186f083bb.png">
http://epsg.io/4230/map and http://epsg.io/4230-1133/map

    $ gdaltransform -s_srs epsg:4326 -t_srs "+proj=longlat +ellps=intl +towgs84=-87,-98,-121,0,0,0,0 +no_defs"
    3 62
    3.00178077731776 62.0004616837349 -29.7889704471454

Do you claim one of these results is numerically incorrect?
If this is the case we should create a new ticket just for that - when you prove why, and provide examples of correct transformation with a reference to software which you have used...

I believe this ticket can be closed. Please confirm.

**Comment by OASteinlein** [comment]
Hi Petr,

What I don’t understand is that your examples below show coordinates at the bottom of the map which are both from the EPSG:1133 transformation. I.e. 1613 is not used in the first one.
My Blue Marble calculations correspond to your command line calculations.

Regards,
Odd

Here are my calculations:

1613:
[cid:image002.png@01D1010B.0CE57F50]

1133:
[cid:image003.png@01D1010B.0CE57F50]

**Comment by klokan** [comment]
I see. I overooked that. The report bug is acknowledged.

The problem is in JavaScript of the /map application. Call to our API is wrong on the page :
http://epsg.io/trans?x=3&y=62&t_srs=4230
instead of:
http://epsg.io/trans?x=3&y=62&t_srs=4230-1613

BTW Could you please drag&drop the screenshots/images to GitHub - they did not go through from your email reply.

**Comment by klokan** [comment]
BTW Do you think we could meet on Skype?

**Comment by OASteinlein** [comment]
Hi Petr,
Yes, we can meet on Skype if you need to discuss this.

Here are my screenshots:

![1613](https://cloud.githubusercontent.com/assets/14936358/10359302/86955ffc-6d97-11e5-8baf-2f298cca6703.gif)
![1133](https://cloud.githubusercontent.com/assets/14936358/10359308/93201a50-6d97-11e5-8b68-b96bbed8469d.gif)

**Comment by klokan** [comment]
It is fixed now.

**Comment by OASteinlein** [comment]
Hi Petr,
Sorry, but it does not work properly. If I typed in Longitude: 3 and Latitude: 60 in the map window 
http://epsg.io/1613/map, the result at the bottom of the screen says 'undefined' 'undefined'. 
Typing in coordinates at the bottom of the screen (lat, lon), gives NaN at the top of the screen. 
I tried the same with 1133 with the same result.
Odd

**Comment by klokan** [comment]
Correct link (also mentioned above) is http://epsg.io/4230-1613/map and http://epsg.io/4230-1133/map
If you search for ED50 and choose the transformation - then these are the links present on the website.

This is the result:
![screen shot 2015-10-19 at 09 29 52](https://cloud.githubusercontent.com/assets/59284/10572043/deef0170-7644-11e5-9944-42cb451d86f2.png)


The link you mentioned is incorrect (and not linked from the website), because 1613 it is only code for transformation - not for a coordinate system (such as ED50 EPSG:4230). But you are right - the web should report you "404 Not found" instead of showing the map interface to avoid confusion in such case - this is reported under #90.

**Comment by OASteinlein** [comment]
Ok, thank you very much!
