### ISSUE TITLE
The UTM zone as API output

### ISSUE THREAD

**Issue by aborruso** [klokantech/epsg.io#96]
Dear all,
is it possible to have UTM zone as API output?

Something like http://epsg.io/trans?x=50&y=17&z=0&s_srs=4326&output=UTM_zone, that gives back:

    jsonpFunction (
    {
    	"y": "17.00000000",
    	"x": "50.00000000",
    	"z": "0.00000000",
    	"UTM_Zone": "39"
    }
    )

Thank you

**Comment by klokan** [comment]
That sounds very non-standard and related to your application....

Most of the coordinate systems does not have any UTM zone.

You should probably put in your application the ranges of lat/lon where the utm zones switches - it is a code for a few lines. I think it does not belong to transformation API.

We were thinking about improvements related to UTM search on the web though #11

**Comment by aborruso** [comment]
Thank you @klokan 

Sure it's not standard. I think it could be useful, because UTM zones are global and it could be very useful to have the UTM zone for a coordinates pair. 
In your great service (thank you) there are all (in example) WGS 84 UTM zones, and for each there is the longitude range: every time I must choose an UTM t_srs I must search what's the zone that match my place.

I know that it's simple to build this system, it was my only hope to have it inside epsg.io.

Thank you for your time

**Comment by klokan** [comment]
If you provide a nice code in a pull request - not breaking anything, we will review it and merge... so it can be part of the service if you want.

**Comment by aborruso** [comment]
@klokan I think I'm not able, but I will try.

Thank you again
