### ISSUE TITLE
Improved /map application

### ISSUE THREAD

**Issue by klokan** [klokantech/epsg.io#97]
The application at http://epsg.io/5514/map should be rewritten into OpenLayers and further improved.

Inspiration from http://twcc.fr/en/ is welcome.

We should have it in two instances, one at http://epsg.io/map (a general one - allowing selection of the coordinate system of choice)

And another to show known coordinates in advance, such as http://epsg.io/5514/map or http://epsg.io/5514-5239/map (with transformation selected).

It should contain features like:
- Permalink for location in hash
- Formatting of the numbers a la twcc - #5 
- Selection of the coordinate system
- Responsive design (mobile optimised) done with @daliborjanak

**Comment by petrsloup** [comment]
- [ ] remove lat/lon boxes
- [ ] responsive layout
- [ ] popup for coordinate system
- [ ] change map layers

**Comment by daliborjanak** [comment]
@petrsloup done. We could deploy it.

**Comment by daliborjanak** [comment]
- [ ] /map add 4325 as default @petrsloup 
- [ ] /map remove border radius on @daliborjanak
